### ISSUE TITLE
File picker not being loaded on wayfire images

### ISSUE THREAD

**Issue by 2Kaleb** [wayblueorg/wayblue#52] opened 2024-07-21 20:22 UTC
https://wiki.archlinux.org/title/XDG_Desktop_Portal#GTK_(possibly_others)_file_chooser_not_working

This is precisely an issue I'm having on Wayblue (Only tested River and Wayfire) since the beginning.
--> Nothing happens on "Open Filer/Folder" for many applications.

Also not sure if relevant, but says UseIn=gnome

**Comment by RoyalOughtness** [comment] 2024-07-21 20:25
@2Kaleb what says "usein=gnome?"

also, is this only for xwayland apps?

**Comment by 2Kaleb** [comment] 2024-07-21 20:29
gtk.portal says usein=gnome, but unsure if relevant

I confirmed it also for Wayland native app

verified with xorg-xeyes

**Comment by RoyalOughtness** [comment] 2024-07-21 20:31
Hm then this is a different issue than what you linked, since that is just for xwayland apps. What apps *are* you able to use the file picker with?

**Comment by 2Kaleb** [comment] 2024-07-21 20:35
I think only those that provide file picker natively like OnlyOffice.
But 90% of the apps I cannot use file picker

**Comment by RoyalOughtness** [comment] 2024-07-21 20:37
ah then the file picker is probably just not being loaded at all, I'll look into this

**Comment by RoyalOughtness** [comment] 2024-07-22 15:41
@2Kaleb can you try installing `xdg-desktop-portal-wlr` and then setting it as the portal in wayfire.ini?

**Comment by 2Kaleb** [comment] 2024-07-24 12:46
I don't understand.
FileChooser is provided by XDG-gtk.

XDG-wlr and XDG-gtk are pre-installed in Image
XDG-wlr doesn't provide FileChooser.

I mean the default install/config should work fine, but It doesn't for me. IDK
```
wlr.portal
-----------------------------------------------------------------
[portal]
DBusName=org.freedesktop.impl.portal.desktop.wlr
Interfaces=org.freedesktop.impl.portal.Screenshot;org.freedesktop.impl.portal.ScreenCast;
UseIn=wlroots;sway;Wayfire;river;phosh;Hyprland;
````
```
gtk.portal
------------------------------------------------------------------
[portal]
DBusName=org.freedesktop.impl.portal.desktop.gtk
Interfaces=org.freedesktop.impl.portal.FileChooser;org.freedesktop.impl.portal.AppChooser;org.freedesktop.impl.portal.Print;org.freedesktop.impl.portal.Notification;org.freedesktop.impl.portal.Inhibit;org.freedesktop.impl.portal.Access;org.freedesktop.impl.portal.Account;org.freedesktop.impl.portal.Email;org.freedesktop.impl.portal.DynamicLauncher;org.freedesktop.impl.portal.Settings;
UseIn=gnome
```

```
wlroots-portals.conf
---------------------------------------------------------------------------
[preferred]
# Use xdg-desktop-portal-gtk for every portal interface...
default=gtk
# ... except for the ScreenCast and Screenshot
org.freedesktop.impl.portal.ScreenCast=wlr
org.freedesktop.impl.portal.Screenshot=wlr
```

**Comment by RoyalOughtness** [comment] 2024-07-24 18:32
@2Kaleb Oh you're right, I misspoke. This will need more investigation. If you figure it out please let me know

**Comment by RoyalOughtness** [comment] 2024-08-10 09:08
Caused by local overrides, fixed by reverting to wayblue config

**Closed as not planned by RoyalOughtness** 2024-08-10 09:08 UTC
Labels: bug
