### ISSUE TITLE
udev rules are not correct

### ISSUE THREAD

**Issue by sgallag-insta** [wayblueorg/wayblue#64] opened 2024-10-20 14:42 UTC
On boot, I see the following errors in the logs:
```
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/10-switch.rules:1 Unknown group 'nintendo_switch', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /etc/udev/rules.d/51-android.rules:206 Invalid key/value pair, ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /etc/udev/rules.d/51-android.rules:207 Invalid key/value pair, ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /etc/udev/rules.d/51-android.rules:517 Invalid key/value pair, ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /etc/udev/rules.d/51-android.rules:518 Invalid key/value pair, ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /etc/udev/rules.d/51-android.rules:521 Invalid key/value pair, ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /etc/udev/rules.d/51-android.rules:157 GOTO="go_adb" has no matching label, ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /etc/udev/rules.d/51-android.rules:158 GOTO="go_adbrndis" has no matching label, ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /etc/udev/rules.d/51-android.rules:159 GOTO="go_adbmtp" has no matching label, ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /etc/udev/rules.d/51-android.rules:160 GOTO="go_adbptp" has no matching label, ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /etc/udev/rules.d/51-android.rules:161 GOTO="go_adbmidi" has no matching label, ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /etc/udev/rules.d/51-android.rules:162 GOTO="go_adb" has no matching label, ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:20 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:23 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:26 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:29 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:32 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:35 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:38 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:41 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:44 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:47 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:50 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:53 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:56 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:59 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:62 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:63 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:66 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:69 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:72 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:75 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:78 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:81 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:84 Unknown group 'plugdev', ignoring.
Oct 20 10:27:01 systemd-udevd[910]: /usr/lib/udev/rules.d/70-u2f.rules:87 Unknown group 'plugdev', ignoring.
```

As far as I can tell there are 2 issues here. 
1. It looks like other ublue images have/are creating a `plugdev` group.
2. Based on [this](https://github.com/ublue-os/bluefin/issues/1478) discussion it seems the android logs _should_ have already been fixed upstream a few months back, but perhaps wayblue is pulling the incorrect package?

**Comment by fiftydinar** [comment] 2024-10-20 16:38
For some reason, older Android udev rule is still pulled from Ublue, so I use this workaround to fix it. (I reported in last comment in linked discussion that it's solved, but it seems it's still not for some reason)

https://github.com/fiftydinar/gidro-os/blob/main/files/scripts/android-udev-rule-workaround.sh

So it's an upstream issue, not Wayblues.

**Comment by RoyalOughtness** [comment] 2024-10-20 18:47
@fiftydinar where is the newer package? I'm pulling from the ublue repo

**Comment by fiftydinar** [comment] 2024-10-20 18:52
> @fiftydinar where is the newer package? I'm pulling from the ublue repo

There is no newer package. The issue is that Ublue's rebuild in COPR somehow didn't include the latest udev rule.

Original spec file is here: https://github.com/M0Rf30/android-udev-rules/blob/main/rpm/android-udev-rules.spec

Ublue just forked this spec without changes to rebuild in ublue-os `staging` COPR repo

**Comment by RoyalOughtness** [comment] 2024-10-20 18:54
oh I see. damn

secureblue needs a fix for this too then

**Comment by RoyalOughtness** [comment] 2024-10-21 00:06
Thanks, @sgallag-insta do you mind also reporting this to ublue?

**Comment by sgallag-insta** [comment] 2024-10-21 01:54
It seems like the ublue/staging repo doesn't really have a ton of issues filed against it, so I'm not sure the best place to bring it up. However, I've posted in their discord about it

**Comment by sgallag-insta** [comment] 2024-10-21 04:03
After some back and forth with the ublue maintainers I can confirm that their latest build **does** include the fix for this issue.

I think we must be calling the wrong URL or something.

**Comment by RoyalOughtness** [comment] 2024-10-24 19:07
@sgallag-insta the old url looks correct:

```
curl -Lo /etc/yum.repos.d/_copr_ublue-os_staging.repo https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-"${OS_VERSION}"/ublue-os-staging-fedora-"${OS_VERSION}".repo
```

this matches:

https://copr.fedorainfracloud.org/coprs/ublue-os/staging/repo/fedora-40/ublue-os-staging-fedora-40.repo

which i directly copied from the copr link

**Comment by sgallag-insta** [comment] 2024-10-24 19:14
@qoijjj Yes, I've spend some more time looking at this but I don't really understand what the problem is.

1. The newest build has the correct file.
2. The staging repo seemingly has the latest build (although it **does** have older builds too.)
3. As you've said, the URL seems correct.

For some reason we are seemingly not getting the latest build from the repo. I've also taken a quick look at what bluefin is doing and it doesn't seem significantly different as far as I can tell :confused:

**Comment by RoyalOughtness** [comment] 2024-10-24 19:26
@sgallag-insta 

ublue-main logs:

```
android-udev-rules-20230310-1.fc41.noarch (copr:copr.fedorainfracloud.org:ublue-os:staging)
```

secureblue logs:

```
android-udev-rules-20230310-1.fc41.noarch (copr:copr.fedorainfracloud.org:ublue-os:staging)
```

**Comment by RoyalOughtness** [comment] 2024-10-24 19:26
what the hell? :|

**Comment by RoyalOughtness** [comment] 2024-10-24 19:38
@sgallag-insta I have a theory.

I think it has something to do with the fact that they're not versioning the spec whatsoever, which means the rpm that gets pulled is arbitrary between one of these four builds?

![image](https://github.com/user-attachments/assets/def3627a-7a8a-4777-abea-25b4a337e58e)

**Comment by RoyalOughtness** [comment] 2024-10-24 19:40
https://github.com/M0Rf30/android-udev-rules/pull/333

**Comment by sgallag-insta** [comment] 2024-10-24 19:41
@qoijjj Yeah, I'm also sus of the whole version number not changing thing. Wouldn't surprise me if it was random (or  always earliest or something)

**Comment by RoyalOughtness** [comment] 2024-10-24 19:42
I submitted that PR upstream of upstream, once it's merged we can go back to the rpm

**Comment by sgallag-insta** [comment] 2024-10-24 19:58
We'll also need to make sure it makes it's way into ublue's fork

https://github.com/ublue-os/android-udev-rules

**Comment by RoyalOughtness** [comment] 2024-10-27 22:23
https://github.com/ublue-os/android-udev-rules/pull/9

**Comment by RoyalOughtness** [comment] 2024-10-30 04:49
merged upstream, reverting the direct pull

https://github.com/wayblueorg/wayblue/commit/5eeef630024ebf9ffb0bcc8f1d046a2ffbb0ce5f

**Closed as completed by RoyalOughtness** 2024-10-30 04:49 UTC
